name: Auto-add Front Matter to Markdown Files

on:
  push:
    branches: ["main"]

# Need write permissions to commit changes
permissions:
  contents: write

jobs:
  add-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add front matter to markdown files
        run: |
          #!/bin/bash
          
          # Find all .md files in documents/ directory (including subdirectories)
          while IFS= read -r file; do
            echo "Checking: $file"
            
            # Read first line of the file
            FIRST_LINE=$(head -n 1 "$file" 2>/dev/null || echo "")
            
            # Check if file starts with front matter delimiter
            if [[ "$FIRST_LINE" != "---" ]]; then
              echo "  → Adding front matter to: $file"
              
              # Create temporary file with front matter + original content
              # Strip leading blank lines from original file to ensure proper Jekyll parsing
              {
                echo "---"
                echo "layout: universal"
                echo "---"
                sed '/./,$!d' "$file"
              } > "$file.tmp"
              
              # Replace original file
              mv "$file.tmp" "$file"
              
              # Mark that we made changes
              touch .frontmatter-modified
            else
              echo "  ✓ Already has front matter"
            fi
          done < <(find documents -type f -name "*.md")

      - name: Commit and push changes
        run: |
          # Check if marker file exists
          if [ -f .frontmatter-modified ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A documents/
            git commit -m "chore: auto-add front matter to markdown files"
            git push
            echo "✅ Front matter added and committed"
          else
            echo "ℹ️ No changes needed - all markdown files already have front matter"
          fi
